'use strict';
const definitions=[
['los','Length of stay (days)',[['<1',36],['1 to <8',4],['8 to <24',0],['24 to <54',5],['≥54',16]]],
['recipient','Recipient age (years)',[['<27',4],['27 to <43',0],['43 to <61',3],['61 to <66',8],['≥66',10]]],
['donor','Donor age (years)',[['<19',0],['19 to <42',2],['42 to <52',7],['≥52',10]]],
['ethnicity','Recipient ethnicity',[['Black',8],['Hispanic',0],['Other',0],['White',1]]],
['diabetes','Recipient diabetes',[['No',0],['Unknown / not reported',2],['Yes',6]]],
['egfr','eGFR (mL/min/1.73 m²)',[['<28',8],['28 to <44.4',5],['44.4 to <88',1],['88 to <109',0],['≥109',1],['Unknown',3]]],
['bilirubin','Total bilirubin (mg/dL)',[['<0.3',2],['0.3 to <0.5',0],['0.5 to <3.2',1],['≥3.2',3],['Unknown',0]]],
['payment','Payment source',[['Government',4],['Other / not reported',3],['Private',0]]],
['smoking','Cigarette use',[['No',0],['Not reported',8],['Yes',5]]],
['diagnosis','Diagnosis',[['Congenital heart disease',2],['Dilated cardiomyopathy',2],['Ischemic cardiomyopathy',8],['Re-transplant / graft failure / valvular / other / rare',5],['Restrictive / hypertrophic cardiomyopathy',0]]]
];
const $=id=>document.getElementById(id);let lookup=null;
for(const [id,label,options] of definitions){const div=document.createElement('div');div.className='field'+(id==='diagnosis'?' full':'');const lab=document.createElement('label');lab.htmlFor=id;lab.textContent=label;const select=document.createElement('select');select.id=id;select.name=id;select.required=true;select.add(new Option('Select a category…',''));options.forEach(([name],i)=>select.add(new Option(name,String(i))));select.addEventListener('change',render);const points=document.createElement('span');points.id=id+'-points';points.className='points';div.append(lab,select,points);if(id==='los'){const note=document.createElement('span');note.className='small';note.textContent='From first transplant to first discharge.';div.append(note);}$('fields').append(div);}
function current(){let total=0,complete=0,undefinedFields=[];for(const [id,label,options] of definitions){const v=$(id).value;if(v==='')continue;complete++;const p=options[Number(v)][1];if(p===null)undefinedFields.push(label);else total+=p;}return{total,complete,undefinedFields};}
function pct(x){return (x*100).toFixed(2)+'%';}
function render(){const s=current();for(const [id,,options] of definitions){const v=$(id).value;$(id+'-points').textContent=v===''?'':options[+v][1]===null?'No scoring rule supplied':options[+v][1]+' points';}$('completion').textContent=s.complete+' of 10 inputs selected'+(s.complete<10?' · partial score':'');$('score').innerHTML=(s.undefinedFields.length?'—':s.total)+'<span> points</span>';$('results').hidden=true;$('status').hidden=false;$('status').className='';if(s.undefinedFields.length){$('status').className='error';$('status').textContent='Cannot calculate: a scoring rule is missing for '+s.undefinedFields.join(', ')+'. Please consult the model author.';return;}if(s.complete<10){$('status').textContent='Complete all ten inputs to see the risk estimates and confidence intervals.';return;}if(!lookup){$('status').textContent='Risk data are not available yet. Please reload if this persists.';return;}const r=lookup.get(s.total);if(!r){$('status').className='error';$('status').textContent='Score '+s.total+' is outside the supplied 0–100 lookup table. Updated bootstrap estimates for this score are required; no extrapolation is shown.';return;}$('status').hidden=true;$('results').hidden=false;const horizons=[1,5,10,15];$('cards').innerHTML=horizons.map(t=>'<div class="metric"><span>'+t+' YEAR'+(t>1?'S':'')+'</span><strong>'+pct(r['risk'+t])+'</strong><small>95% CI '+(100*r['risk'+t+'_lower']).toFixed(2)+'–'+(100*r['risk'+t+'_upper']).toFixed(2)+'%</small></div>').join('');$('values').innerHTML=horizons.map(t=>'<tr><td>'+t+' year'+(t>1?'s':'')+'</td><td>'+pct(r['risk'+t])+'</td><td>'+pct(r['risk'+t+'_lower'])+' – '+pct(r['risk'+t+'_upper'])+'</td></tr>').join('');draw(r);}
function probabilityColor(p){return `hsl(${120*(1-Math.max(0,Math.min(1,p)))},65%,35%)`;}
function draw(r){const y=p=>275-p*230;let svg='<text x="45" y="20" fill="#536c7e" font-size="13">Event probability (%)</text>';for(let p=0;p<=100;p+=25){svg+='<line x1="48" x2="617" y1="'+y(p/100)+'" y2="'+y(p/100)+'" stroke="#e2ebef"/><text x="35" y="'+(y(p/100)+5)+'" text-anchor="end" fill="#637b8a" font-size="13">'+p+'</text>';}
[1,5,10,15].forEach((t,i)=>{const x=100+i*160,v=r['risk'+t],lo=r['risk'+t+'_lower'],hi=r['risk'+t+'_upper'],color=probabilityColor(v);svg+='<g tabindex="0"><title>'+t+' years: '+pct(v)+', 95% CI '+pct(lo)+' to '+pct(hi)+'</title><line x1="'+x+'" x2="'+x+'" y1="'+y(lo)+'" y2="'+y(hi)+'" stroke="'+color+'" stroke-width="3"/><path d="M'+(x-10)+' '+y(lo)+'h20 M'+(x-10)+' '+y(hi)+'h20" stroke="'+color+'" stroke-width="2"/><circle cx="'+x+'" cy="'+y(v)+'" r="6" fill="'+color+'" stroke="white" stroke-width="2"/><text x="'+x+'" y="303" text-anchor="middle" fill="#435e71" font-size="14">'+t+' year'+(t>1?'s':'')+'</text></g>';});$('chart').innerHTML=svg;}
$('reset').onclick=()=>{$('form').reset();render();};$('form').onsubmit=e=>e.preventDefault();
fetch('risks.json').then(r=>{if(!r.ok)throw Error('load');return r.json();}).then(rows=>{lookup=new Map(rows.map(r=>[r.heart_score,r]));render();}).catch(()=>{$('status').textContent='Unable to load risk estimates. Please reload the page.';});render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();Promise.resolve(document.modelContext.registerTool({name:'set_patient_categories',description:'Set all ten category indices (zero-based) in the visible research calculator. Read the supplied category definitions first.',inputSchema:{type:'object',properties:{categories:{type:'object',properties:Object.fromEntries(definitions.map(([id,,o])=>[id,{type:'integer',minimum:0,maximum:o.length-1}])),required:definitions.map(d=>d[0]),additionalProperties:false}},required:['categories'],additionalProperties:false},execute:async input=>{for(const[id,,o]of definitions){const v=input?.categories?.[id];if(!Number.isInteger(v)||v<0||v>=o.length)throw Error('Invalid category: '+id);}for(const[id]of definitions)$(id).value=String(input.categories[id]);render();const s=current();return{...s,risk:s.complete===10&&!s.undefinedFields.length?lookup?.get(s.total)??null:null};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
